id: P4F883940
initial_creation_type: ocr
source_metadata:
  volumes:
    86e117716307432785bacdae06efaf34:
      base_file: v077.txt
      image_group_id: I1PD95922
      title: ལས་གྲུབ་པའི་རབ་ཏུ་བྱེད་པ།
      total_pages: 1517
      volume_number: 77
